import subprocess
import sys
import os
import time
from datetime import datetime
import streamlit as st
import requests
import yaml

st.set_page_config(
    page_title="DevOps Workflow Agent",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

BACKEND_PORT = 8000
BACKEND_URL = f"http://localhost:{BACKEND_PORT}"
SAMPLE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sample_data")
WORKERS = 4


@st.cache_resource(show_spinner=False)
def start_backend():
    cwd = os.path.dirname(os.path.abspath(__file__))
    cmd = [
    sys.executable,
    "-m",
    "uvicorn",
    "backend.main:app",
    "--host",
    "0.0.0.0",
    "--port",
    str(BACKEND_PORT),
    ]
    proc = subprocess.Popen(cmd, cwd=cwd, env={**os.environ},
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(30):
        try:
            r = requests.get(f"{BACKEND_URL}/health", timeout=1)
            if r.status_code == 200:
                return proc
        except Exception:
            time.sleep(1)
    return proc


def load_sample(filename: str) -> str:
    with open(os.path.join(SAMPLE_PATH, filename), "r") as f:
        return f.read()


def get_health() -> dict:
    try:
        r = requests.get(f"{BACKEND_URL}/health", timeout=3)
        if r.status_code == 200:
            return r.json()
    except Exception:
        pass
    return None


def severity_badge(severity: str) -> str:
    return {"CRITICAL": "🔴 CRITICAL", "HIGH": "🟠 HIGH",
            "MEDIUM": "🟡 MEDIUM", "LOW": "🟢 LOW"}.get(severity or "", "⚪ UNKNOWN")


# ── Download Report ───────────────────────────────────────────────────────────
def build_report_markdown(result: dict, filename: str) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    sev = result.get("severity", "UNKNOWN")
    conf = int((result.get("confidence_score") or 0) * 100)
    masked = result.get("masked_secrets", [])

    lines = [
        f"# DevOps Workflow Agent — Analysis Report",
        f"",
        f"**File analysed:** `{filename}`  ",
        f"**Generated:** {now}  ",
        f"**Severity:** {sev}  ",
        f"**Confidence:** {conf}%  ",
        f"",
    ]

    if masked:
        lines += [
            "## 🔐 Secret Masking",
            f"_{len(masked)} sensitive item(s) were automatically redacted before AI analysis:_",
            "",
        ]
        for item in masked:
            lines.append(f"- `{item}`")
        lines.append("")

    sections = [
        ("## 🔍 Root Cause Analysis",    result.get("root_cause")),
        ("## 🔧 Fix Suggestions",         result.get("fix_suggestions")),
        ("## 🔒 Security Issues",         result.get("security_issues")),
        ("## 📖 Failure Explanation",     result.get("explanation")),
        ("## ✅ Prevention Recommendations", result.get("prevention")),
    ]
    for header, content in sections:
        lines.append(header)
        lines.append("")
        lines.append(content or "_Not available._")
        lines.append("")

    lines += [
        "---",
        "_Report generated by DevOps Workflow Agent · LangGraph + FastAPI + Streamlit_",
    ]
    return "\n".join(lines)


def render_download_button(result: dict, filename: str):
    md = build_report_markdown(result, filename)
    safe_name = filename.replace("/", "_").replace("\\", "_")
    st.download_button(
        label="📥 Download Report (.md)",
        data=md.encode("utf-8"),
        file_name=f"devops_report_{safe_name}_{datetime.utcnow().strftime('%Y%m%d_%H%M')}.md",
        mime="text/markdown",
        use_container_width=True,
    )


# ── Secret Masking Banner ─────────────────────────────────────────────────────
def render_mask_report(masked_items: list):
    if not masked_items:
        return
    with st.expander(
        f"🔐 Secret Masker — {len(masked_items)} item(s) redacted before AI saw this file",
        expanded=True,
    ):
        st.success(
            "These values were **replaced with labeled placeholders** before the content "
            "reached the AI. The actual secrets were never transmitted."
        )
        for item in masked_items:
            st.markdown(f"- `{item}`")


# ── Resolve Button ────────────────────────────────────────────────────────────
def render_resolve_button(analysis_id: int):
    key = f"resolved_{analysis_id}"
    if st.session_state.get(key):
        st.success("✅ Marked as resolved — counted in your resolution stats.")
        return
    if st.button("✅ Mark as Resolved", key=f"btn_{analysis_id}", use_container_width=True):
        try:
            resp = requests.post(f"{BACKEND_URL}/api/analyses/{analysis_id}/resolve", timeout=5)
            if resp.ok:
                st.session_state[key] = True
                st.rerun()
            else:
                st.warning("Could not mark resolved — may already be resolved.")
        except Exception as e:
            st.error(f"Error: {e}")


# ── Analysis Result Panel ─────────────────────────────────────────────────────
def render_analysis(result: dict, filename: str = "analysis"):
    render_mask_report(result.get("masked_secrets", []))

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Severity", severity_badge(result.get("severity", "LOW")))
    with col2:
        score = result.get("confidence_score", 0.5)
        icon = "🟢" if score >= 0.8 else ("🟡" if score >= 0.6 else "🔴")
        st.metric("Confidence", f"{icon} {int(score * 100)}%")
    with col3:
        verified = result.get("verified_fix", False)
        exit_code = result.get("sandbox_exit_code")
        st.metric("Fix Validated", "✅ Yes" if verified else "🔲 No",
                  delta=f"Exit code: {exit_code}" if exit_code is not None else None)

    st.divider()
    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "🔍 Root Cause", "🔧 Fix Suggestions", "🔒 Security", "📖 Explanation", "✅ Prevention"
    ])
    with tab1:
        st.subheader("Root Cause Analysis")
        st.markdown(result.get("root_cause") or "_No root cause identified._")
    with tab2:
        st.subheader("Fix Suggestions")
        st.markdown(result.get("fix_suggestions") or "_No fix suggestions._")
    with tab3:
        st.subheader("Security Issues")
        sec = result.get("security_issues", "")
        if sec and any(kw in sec.lower() for kw in ["hardcoded", "exposed", "critical", "secret", "password", "key"]):
            st.error("⚠️ Security vulnerabilities detected — review immediately.")
        st.markdown(sec or "_No security issues found._")
    with tab4:
        st.subheader("Failure Explanation")
        st.markdown(result.get("explanation") or "_No explanation available._")
    with tab5:
        st.subheader("Prevention Recommendations")
        st.markdown(result.get("prevention") or "_No recommendations._")

    st.divider()
    action_col1, action_col2 = st.columns(2)
    with action_col1:
        render_download_button(result, filename)
    with action_col2:
        analysis_id = result.get("analysis_id")
        if analysis_id:
            render_resolve_button(analysis_id)


# ── Analytics Dashboard ───────────────────────────────────────────────────────
def render_analytics():
    import plotly.graph_objects as go
    import plotly.express as px

    st.subheader("📊 Analytics Dashboard")

    try:
        resp = requests.get(f"{BACKEND_URL}/api/analytics", timeout=5)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        st.error(f"Could not load analytics: {e}")
        return

    total_analyses = sum(data.get("type_dist", {}).values())
    sev = data.get("severity_dist", {})
    avg_hours = data.get("avg_resolution_hours")

    if total_analyses == 0:
        st.info("No analyses recorded yet — run some analyses to see charts here.")
        return

    # KPI row
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Analyses", total_analyses)
    with col2:
        criticals = sev.get("CRITICAL", 0) + sev.get("HIGH", 0)
        st.metric("Critical / High", criticals)
    with col3:
        total_secrets = sum(d["masked"] for d in data.get("secrets_trend", []))
        st.metric("Secrets Masked", total_secrets)
    with col4:
        if avg_hours is not None:
            st.metric("Avg Resolution Time", f"{avg_hours}h")
        else:
            st.metric("Avg Resolution Time", "—")

    st.divider()

    # Row 1: Daily trend + Severity pie
    left, right = st.columns([3, 2])
    with left:
        daily = data.get("daily_trend", [])
        if daily:
            days = [d["day"] for d in daily]
            totals = [d["total"] for d in daily]
            resolveds = [d["resolved"] for d in daily]
            fig = go.Figure()
            fig.add_trace(go.Bar(name="Total", x=days, y=totals,
                                  marker_color="#4F8EF7"))
            fig.add_trace(go.Bar(name="Resolved", x=days, y=resolveds,
                                  marker_color="#22C55E"))
            fig.update_layout(
                title="Analyses per Day (last 30 days)",
                barmode="overlay",
                height=300,
                margin=dict(l=0, r=0, t=40, b=0),
                legend=dict(orientation="h", yanchor="bottom", y=1.02),
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("No daily trend data yet (need analyses from multiple days).")

    with right:
        if sev:
            sev_colors = {
                "CRITICAL": "#EF4444", "HIGH": "#F97316",
                "MEDIUM": "#EAB308", "LOW": "#22C55E"
            }
            fig2 = px.pie(
                names=list(sev.keys()),
                values=list(sev.values()),
                color=list(sev.keys()),
                color_discrete_map=sev_colors,
                title="Severity Distribution",
            )
            fig2.update_layout(height=300, margin=dict(l=0, r=0, t=40, b=0))
            st.plotly_chart(fig2, use_container_width=True)

    # Row 2: Type breakdown + Secrets trend
    left2, right2 = st.columns([2, 3])
    with left2:
        type_dist = data.get("type_dist", {})
        if type_dist:
            type_colors = {"log": "#4F8EF7", "yaml": "#A855F7",
                           "combined": "#F97316", "repo": "#22C55E"}
            fig3 = px.bar(
                x=list(type_dist.keys()),
                y=list(type_dist.values()),
                color=list(type_dist.keys()),
                color_discrete_map=type_colors,
                labels={"x": "Type", "y": "Count"},
                title="By Analysis Type",
            )
            fig3.update_layout(
                height=280, showlegend=False,
                margin=dict(l=0, r=0, t=40, b=0),
            )
            st.plotly_chart(fig3, use_container_width=True)

    with right2:
        secrets = data.get("secrets_trend", [])
        if secrets and any(d["masked"] > 0 for d in secrets):
            fig4 = go.Figure()
            fig4.add_trace(go.Scatter(
                x=[d["day"] for d in secrets],
                y=[d["masked"] for d in secrets],
                mode="lines+markers",
                fill="tozeroy",
                line=dict(color="#F97316"),
                name="Secrets Masked",
            ))
            fig4.update_layout(
                title="Secrets Masked Before AI (per day)",
                height=280,
                margin=dict(l=0, r=0, t=40, b=0),
            )
            st.plotly_chart(fig4, use_container_width=True)
        else:
            st.info("No secrets masked yet in the last 30 days.")

    # Row 3: Weekly resolution rate
    weekly = data.get("weekly_resolution", [])
    if len(weekly) > 1:
        st.subheader("Weekly Resolution Rate")
        fig5 = go.Figure()
        fig5.add_trace(go.Scatter(
            x=[w["week"] for w in weekly],
            y=[w["rate"] for w in weekly],
            mode="lines+markers+text",
            text=[f"{w['rate']}%" for w in weekly],
            textposition="top center",
            line=dict(color="#22C55E", width=2),
            fill="tozeroy",
            fillcolor="rgba(34,197,94,0.1)",
        ))
        fig5.update_layout(
            yaxis=dict(range=[0, 105], ticksuffix="%"),
            height=260,
            margin=dict(l=0, r=0, t=10, b=0),
        )
        st.plotly_chart(fig5, use_container_width=True)

    # Average confidence by type
    avg_conf = data.get("avg_confidence", {})
    if avg_conf:
        st.subheader("Average Confidence Score by Analysis Type")
        conf_cols = st.columns(len(avg_conf))
        for col, (atype, val) in zip(conf_cols, avg_conf.items()):
            icon = "🟢" if val >= 0.8 else ("🟡" if val >= 0.6 else "🔴")
            col.metric(atype.upper(), f"{icon} {int(val * 100)}%")


# ── History Tab ───────────────────────────────────────────────────────────────
def render_history_tab():
    st.subheader("📜 Analysis History")
    try:
        resp = requests.get(f"{BACKEND_URL}/api/analyses?limit=30", timeout=5)
        resp.raise_for_status()
        rows = resp.json().get("analyses", [])
    except Exception as e:
        st.error(f"Could not load history: {e}")
        return

    if not rows:
        st.info("No analyses recorded yet.")
        return

    for row in rows:
        icon = "✅" if row["resolved"] else "⏳"
        sev_icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(row.get("severity", ""), "⚪")
        label = (
            f"{icon} #{row['id']} · {row['analysis_type'].upper()} · "
            f"{sev_icon} {row.get('severity', '?')} · {row['filename']} · "
            f"{row['created_at'][:16].replace('T', ' ')} UTC"
        )
        with st.expander(label):
            col1, col2 = st.columns(2)
            with col1:
                st.write(f"**Type:** {row['analysis_type']}")
                st.write(f"**File:** {row['filename']}")
                st.write(f"**Severity:** {severity_badge(row.get('severity', ''))}")
            with col2:
                conf = row.get("confidence_score") or 0
                st.write(f"**Confidence:** {int(conf * 100)}%")
                st.write(f"**Secrets masked:** {row.get('secrets_found', 0)}")
                st.write(f"**Status:** {'✅ Resolved' if row['resolved'] else '⏳ Pending'}")
            if row.get("root_cause_preview"):
                st.caption(f"**Root cause preview:** {row['root_cause_preview']}")
            if not row["resolved"]:
                key = f"resolved_{row['id']}"
                if st.session_state.get(key):
                    st.success("Resolved ✅")
                elif st.button("✅ Mark as Resolved", key=f"hist_btn_{row['id']}"):
                    r = requests.post(f"{BACKEND_URL}/api/analyses/{row['id']}/resolve", timeout=5)
                    if r.ok:
                        st.session_state[key] = True
                        st.rerun()


# ── Evaluation ────────────────────────────────────────────────────────────────
def render_evaluation(report: dict):
    st.subheader("📊 Evaluation Results")
    overall = report.get("overall_score", 0)
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        color = "🟢" if overall >= 75 else ("🟡" if overall >= 55 else "🔴")
        st.metric("Overall Score", f"{color} {overall}/100")
    with col2:
        st.metric("Tests Run", report.get("total_tests", 0))
    with col3:
        st.metric("Passed (≥70)", report.get("passed", 0))
    with col4:
        st.metric("Pass Rate", f"{report.get('pass_rate', 0)}%")
    st.progress(overall / 100, text=f"Overall quality score: {overall}%")
    st.divider()
    for r in report.get("results", []):
        icon = "✅" if r["passed"] else "❌"
        with st.expander(
            f"{icon} [{r['id']}] {r['name']} — {r['score']}/100 · {r['latency_seconds']}s",
            expanded=not r["passed"],
        ):
            bd = r.get("breakdown", {})
            c1, c2, c3, c4 = st.columns(4)
            with c1:
                s = bd.get("sections", {})
                st.metric("Sections", f"{s.get('score', 0)}/{s.get('max', 25)}")
            with c2:
                rc = bd.get("root_cause", {})
                st.metric("Root Cause", f"{rc.get('score', 0)}/{rc.get('max', 30)}")
            with c3:
                fx = bd.get("fixes", {})
                st.metric("Fix Quality", f"{fx.get('score', 0)}/{fx.get('max', 25)}")
            with c4:
                sk = bd.get("security", {})
                st.metric("Security", f"{sk.get('score', 0)}/{sk.get('max', 20)}")
            rc_found = bd.get("root_cause", {}).get("found", [])
            rc_missed = bd.get("root_cause", {}).get("missed", [])
            if rc_found:
                st.success(f"Root cause keywords found: {', '.join(rc_found)}")
            if rc_missed:
                st.warning(f"Root cause keywords missed: {', '.join(rc_missed)}")
            sec_missing = bd.get("sections", {}).get("missing", [])
            if sec_missing:
                st.error(f"Missing output sections: {', '.join(sec_missing)}")
            with st.expander("Agent Output Preview"):
                st.markdown(r.get("agent_output_preview", "_No output_"))





# ── Scanning Helper ───────────────────────────────────────────────────────────
def pre_scan(content: str):
    try:
        scan = requests.post(f"{BACKEND_URL}/api/scan/secrets",
                             json={"content": content}, timeout=5)
        if scan.ok:
            sd = scan.json()
            if sd["secrets_found"] > 0:
                st.warning(
                    f"🔐 **{sd['secrets_found']} sensitive item(s) detected** — "
                    "will be masked before AI analysis."
                )
                with st.expander("See what will be masked"):
                    for f in sd["findings"]:
                        st.markdown(f"- `{f}`")
    except Exception:
        pass


# ═════════════════════════════════════════════════════════════════════════════
def main():
    with st.spinner("Starting AI backend..."):
        start_backend()

    st.title("🤖 DevOps Workflow Agent")
    st.caption("LangGraph · FastAPI · SQLite · Secret Masking · Auto-Fix · Analytics · 4-Worker Backend")

    health = get_health()
    if not health:
        st.error("Backend API is still starting — please wait a moment and refresh.")
        st.stop()

    with st.sidebar:
        st.header("⚙️ Analysis Mode")
        mode = st.radio("Select Mode", [
            "Agentic Repo Analysis",
            "Log File Analysis",
            "YAML Config Audit",
            "Combined Analysis",
            "📊 Analytics",
            "📜 History",
            "🧪 Evaluation Suite",
        ], index=0)

        
        if mode not in ["Agentic Repo Analysis", "🧪 Evaluation Suite",
                        "📜 History", "📊 Analytics"]:
            st.header("📂 Sample Data")
            if st.button("GitHub Actions Failure", use_container_width=True):
                st.session_state["sample_log"] = load_sample("github_actions_failure.log")
                st.session_state["sample_log_name"] = "github_actions_failure.log"
                st.toast("GitHub Actions log loaded!", icon="✅")
            if st.button("Docker Build Failure", use_container_width=True):
                st.session_state["sample_log"] = load_sample("docker_build_failure.log")
                st.session_state["sample_log_name"] = "docker_build_failure.log"
                st.toast("Docker build log loaded!", icon="✅")
            if st.button("Insecure Pipeline YAML", use_container_width=True):
                st.session_state["sample_yaml"] = load_sample("pipeline.yaml")
                st.session_state["sample_yaml_name"] = "pipeline.yaml"
                st.toast("Pipeline YAML loaded!", icon="✅")

        

    # ── AGENTIC REPO ──────────────────────────────────────────────────────────
    if mode == "Agentic Repo Analysis":
        st.subheader("📂 Agentic Repository Investigation")
        st.info("The agent walks your repo, reads CI/CD configs and log tails, then delivers a full analysis.")
        col1, col2 = st.columns([1, 2])
        with col1:
            repo_path = st.text_input("Repo Path", value=".")
        with col2:
            user_query = st.text_area("Analysis Request", height=120,
                placeholder="e.g., Check my GitHub workflows for security risks.")
        if st.button("🚀 Run Agent", type="primary"):
            if not user_query.strip():
                st.warning("Please enter an analysis request.")
            else:
                with st.status("Agent exploring repository...", expanded=True) as status:
                    try:
                        resp = requests.post(f"{BACKEND_URL}/api/analyze/repo",
                            json={"repo_path": repo_path, "query": user_query}, timeout=120)
                        if resp.status_code == 429:
                            st.warning("Rate limit reached — please wait a minute.")
                            status.update(label="Rate limited", state="error")
                        else:
                            resp.raise_for_status()
                            data = resp.json()
                            st.markdown("### Analysis Result")
                            st.markdown(data["result"])
                            st.caption(f"Completed in {data.get('latency_seconds', '?')}s")
                            if data.get("analysis_id"):
                                render_resolve_button(data["analysis_id"])
                            status.update(label="Complete!", state="complete")
                    except Exception as e:
                        st.error(f"Error: {e}")
                        status.update(label="Error", state="error")

    # ── LOG FILE ──────────────────────────────────────────────────────────────
    elif mode == "Log File Analysis":
        st.subheader("📋 CI/CD Log Analysis")
        uploaded = st.file_uploader("Upload log file (.log, .txt)", type=["log", "txt"])
        content, filename = "", "pipeline.log"
        if uploaded:
            content = uploaded.read().decode("utf-8", errors="replace")
            filename = uploaded.name
            st.success(f"Loaded: `{filename}` · {len(content.splitlines())} lines")
        elif "sample_log" in st.session_state:
            content = st.session_state["sample_log"]
            filename = st.session_state.get("sample_log_name", "sample.log")
            st.info(f"Using sample: `{filename}`")

        if content:
            pre_scan(content)
            with st.expander("Preview"):
                st.code(content[:2000] + ("..." if len(content) > 2000 else ""), language="text")
            if st.button("🔍 Analyze", type="primary", use_container_width=True):
                with st.spinner("LangGraph agent analyzing..."):
                    try:
                        resp = requests.post(f"{BACKEND_URL}/api/analyze/log",
                            json={"content": content, "filename": filename}, timeout=120)
                        if resp.status_code == 429:
                            st.warning("Rate limit reached — please wait a minute.")
                        else:
                            resp.raise_for_status()
                            st.session_state["log_result"] = resp.json()
                            st.session_state["log_filename"] = filename
                            st.success("Analysis complete!")
                    except Exception as e:
                        st.error(f"Error: {e}")

        if "log_result" in st.session_state and mode == "Log File Analysis":
            render_analysis(st.session_state["log_result"],
                            st.session_state.get("log_filename", "log"))
        elif not content:
            st.info("Upload a log file or load a sample from the sidebar.")

    # ── YAML AUDIT ────────────────────────────────────────────────────────────
    elif mode == "YAML Config Audit":
        st.subheader("📄 Pipeline YAML Security Audit")
        uploaded = st.file_uploader("Upload YAML config (.yaml, .yml)", type=["yaml", "yml"])
        content, filename = "", "pipeline.yaml"
        if uploaded:
            content = uploaded.read().decode("utf-8", errors="replace")
            filename = uploaded.name
            st.success(f"Loaded: `{filename}`")
        elif "sample_yaml" in st.session_state:
            content = st.session_state["sample_yaml"]
            filename = st.session_state.get("sample_yaml_name", "sample.yaml")
            st.info(f"Using sample: `{filename}`")

        if content:
            try:
                yaml.safe_load(content)
                st.success("Valid YAML syntax ✓")
            except yaml.YAMLError as e:
                st.warning(f"YAML issue: {e}")
            pre_scan(content)
            with st.expander("Preview original"):
                st.code(content[:2000] + ("..." if len(content) > 2000 else ""), language="yaml")

            action_col1, action_col2 = st.columns(2)
            with action_col1:
                run_analysis = st.button("🔍 AI Audit", type="primary", use_container_width=True)
            with action_col2:
                run_autofix = st.button("🔧 Auto-Fix YAML", use_container_width=True)

            if run_analysis:
                with st.spinner("LangGraph agent auditing..."):
                    try:
                        resp = requests.post(f"{BACKEND_URL}/api/analyze/yaml",
                            json={"content": content, "filename": filename}, timeout=120)
                        if resp.status_code == 429:
                            st.warning("Rate limit reached — please wait a minute.")
                        else:
                            resp.raise_for_status()
                            st.session_state["yaml_result"] = resp.json()
                            st.session_state["yaml_filename"] = filename
                            st.success("Audit complete!")
                    except Exception as e:
                        st.error(f"Error: {e}")

            if run_autofix:
                with st.spinner("Applying rule-based fixes..."):
                    try:
                        resp = requests.post(f"{BACKEND_URL}/api/fix/yaml",
                                             json={"content": content}, timeout=60)
                        resp.raise_for_status()
                        st.session_state["yaml_fix"] = resp.json()
                    except Exception as e:
                        st.error(f"Auto-fix error: {e}")

        # Show auto-fix result
        if "yaml_fix" in st.session_state and mode == "YAML Config Audit":
            fix = st.session_state["yaml_fix"]
            st.divider()
            st.subheader("🔧 Auto-Fix Results")
            if not fix["changed"]:
                st.success("No rule-based issues found — YAML looks clean!")
            else:
                st.success(f"**{fix['rules_count']} fix(es) applied automatically:**")
                if fix.get("verified_fix"):
                    st.success("🐳 Docker Validation Passed")
                else:
                    st.error("🐳 Docker Validation Failed")
                for rule in fix["rules_applied"]:
                    
                    st.markdown(f"- ✅ {rule}")

                fix_col1, fix_col2 = st.columns(2)
                with fix_col1:
                    with st.expander("📄 Fixed YAML", expanded=True):
                        st.code(fix["fixed_yaml"], language="yaml")
                    st.download_button(
                        "📥 Download Fixed YAML",
                        data=fix["fixed_yaml"].encode(),
                        file_name=f"fixed_{filename}",
                        mime="text/yaml",
                        use_container_width=True,
                    )
                with fix_col2:
                    with st.expander("📋 Diff", expanded=True):
                        diff_text = fix.get("diff", "")
                        if diff_text:
                            st.code(diff_text, language="diff")
                        else:
                            st.info("No diff available.")
                with st.expander("🐳 Docker Validation Logs", expanded=False):

                    st.write(
                        f"Exit Code: {fix.get('sandbox_exit_code')}"
                    )

                    if fix.get("sandbox_stdout"):
                        st.code(fix["sandbox_stdout"])

                    if fix.get("sandbox_stderr"):
                        st.code(fix["sandbox_stderr"])
        if "yaml_result" in st.session_state and mode == "YAML Config Audit":
            st.divider()
            render_analysis(st.session_state["yaml_result"],
                            st.session_state.get("yaml_filename", "yaml"))
        elif not content:
            st.info("Upload a YAML file or load the sample from the sidebar.")

    # ── COMBINED ──────────────────────────────────────────────────────────────
    elif mode == "Combined Analysis":
        st.subheader("🔗 Cross-Referenced Log + YAML Analysis")
        col1, col2 = st.columns(2)
        with col1:
            up_log = st.file_uploader("Log file", type=["log", "txt"], key="clog")
        with col2:
            up_yaml = st.file_uploader("YAML config", type=["yaml", "yml"], key="cyaml")

        log_c, log_f = "", "pipeline.log"
        yaml_c, yaml_f = "", "pipeline.yaml"
        if up_log:
            log_c, log_f = up_log.read().decode("utf-8", errors="replace"), up_log.name
        elif "sample_log" in st.session_state:
            log_c = st.session_state["sample_log"]
            log_f = st.session_state.get("sample_log_name", "sample.log")
        if up_yaml:
            yaml_c, yaml_f = up_yaml.read().decode("utf-8", errors="replace"), up_yaml.name
        elif "sample_yaml" in st.session_state:
            yaml_c = st.session_state["sample_yaml"]
            yaml_f = st.session_state.get("sample_yaml_name", "sample.yaml")

        sc1, sc2 = st.columns(2)
        with sc1:
            st.success(f"Log: `{log_f}` ✓") if log_c else st.warning("No log file loaded.")
        with sc2:
            st.success(f"YAML: `{yaml_f}` ✓") if yaml_c else st.warning("No YAML file loaded.")

        if log_c or yaml_c:
            pre_scan(log_c + "\n" + yaml_c)

        if log_c and yaml_c:
            if st.button("🔍 Run Combined Analysis", type="primary", use_container_width=True):
                with st.spinner("Cross-referenced analysis..."):
                    try:
                        resp = requests.post(f"{BACKEND_URL}/api/analyze/combined",
                            json={"log_content": log_c, "yaml_content": yaml_c,
                                  "log_filename": log_f, "yaml_filename": yaml_f},
                            timeout=120)
                        if resp.status_code == 429:
                            st.warning("Rate limit reached — please wait a minute.")
                        else:
                            resp.raise_for_status()
                            st.session_state["combined_result"] = resp.json()
                            st.session_state["combined_filename"] = f"{log_f}+{yaml_f}"
                            st.success("Analysis complete!")
                    except Exception as e:
                        st.error(f"Error: {e}")
        elif log_c or yaml_c:
            st.info("Load both files to run combined analysis.")

        if "combined_result" in st.session_state and mode == "Combined Analysis":
            render_analysis(st.session_state["combined_result"],
                            st.session_state.get("combined_filename", "combined"))

    # ── ANALYTICS ─────────────────────────────────────────────────────────────
    elif mode == "📊 Analytics":
        render_analytics()

    # ── HISTORY ───────────────────────────────────────────────────────────────
    elif mode == "📜 History":
        render_history_tab()

    # ── EVALUATION ────────────────────────────────────────────────────────────
    elif mode == "🧪 Evaluation Suite":
        st.subheader("🧪 Agent Evaluation — Golden Dataset")
        st.info(
            "Runs the LangGraph agent against 4 pre-defined test cases and scores output on "
            "**root-cause accuracy**, **fix quality**, **security coverage**, and **section completeness**."
        )
        col1, col2 = st.columns([2, 1])
        with col1:
            st.markdown("""
| ID | Test Case | Type | Expected Severity |
|----|-----------|------|------------------|
| golden_001 | NPM dependency resolve failure | log | HIGH |
| golden_002 | Docker build OOM (exit 137) | log | CRITICAL |
| golden_003 | Insecure pipeline YAML (hardcoded secrets) | yaml | CRITICAL |
| golden_004 | GitHub Actions pytest DB connection failure | log | HIGH |
""")
        with col2:
            st.markdown("**Scoring rubric**")
            st.markdown("- Sections present: 25 pts")
            st.markdown("- Root cause keywords: 30 pts")
            st.markdown("- Fix quality keywords: 25 pts")
            st.markdown("- Security coverage: 20 pts")
            st.markdown("- **Pass threshold: 70/100**")

        st.warning("⏱ Running all 4 tests makes 4 AI calls — expect 2–5 minutes.")
        test_subset = st.multiselect(
            "Run specific tests (empty = run all)",
            ["golden_001", "golden_002", "golden_003", "golden_004"],
        )
        if st.button("▶️ Run Evaluation", type="primary"):
            body = {"test_ids": test_subset} if test_subset else {}
            with st.status("Running evaluation suite...", expanded=True) as status:
                try:
                    resp = requests.post(f"{BACKEND_URL}/api/evaluate", json=body, timeout=300)
                    if resp.status_code == 429:
                        st.warning("Rate limited — capped at 2 runs/min.")
                        status.update(label="Rate limited", state="error")
                    else:
                        resp.raise_for_status()
                        st.session_state["eval_result"] = resp.json()
                        status.update(label="Evaluation complete!", state="complete")
                except Exception as e:
                    st.error(f"Evaluation error: {e}")
                    status.update(label="Error", state="error")

        if "eval_result" in st.session_state:
            render_evaluation(st.session_state["eval_result"])


if __name__ == "__main__":
    main()
